name: flutter_smart
description: Flutter toolkit.
version: 0.0.4
homepage: https://github.com/lsmya/flutter-smart

topics:
  - toolkit

environment:
  sdk: ^3.10.4
  flutter: '>=3.3.0'

dependencies:
  cached_network_image: ^3.4.1
  event_bus: ^2.0.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.1
  image_picker: ^1.2.1
  photo_view: ^0.15.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

flutter:
  assets:
    - assets/images/