name: flutter_smart
description: Flutter toolkit.
version: 0.0.1
homepage: https://github.com/lsmyan/flutter_smart

topics:
  - toolkit

environment:
  sdk: ^3.10.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web: